### ISSUE TITLE
Scrobbling do not works anymore

### ISSUE THREAD

**Issue by apometron** [gix/foo_scrobble#2]
Here it is the log:

foo_scrobble: Queuing scrobble (Unauthenticated)
foo_scrobble: NowPlaying notification failed (error: 9, Invalid session key. Please re-authenticate.)

I cant solve this.

I did tried with various browsers and it stays the same.

Please, help me.

Foobar 1.4 beta 9.

**Comment by Barough** [comment]
Have u tried with removing foo_scrobble from fb2k and then restart it and re-add foo_scrobble and authenticate it again

**Comment by gix** [comment]
What does the log say when authenticating? It should look like this:

    foo_scrobble: Requesting auth token
    foo_scrobble: Received auth token: FyEklwB1ZLpvFYd1BvBO76rzRWz4ThuT
    foo_scrobble: Requesting session key
    foo_scrobble: New session key: _AijaIJbA789aA7NMXmanQLKalG8zqDY

**Comment by apometron** [comment]
Reinstalled, not works. I also installed the MS Visual C++ requisite for Windows 10.

foo_scrobble: Queuing scrobble (Unauthenticated)
foo_scrobble: Queuing scrobble (Unauthenticated)
foo_scrobble: Requesting auth token
foo_scrobble: Received auth token: a_C06aaRCCvYTAohAMlTU1RVR-vyu4NC
foo_scrobble: NowPlaying notification failed (error: 9, Invalid session key. Please re-authenticate.)

Nothing works...

The other scrobbler is ancient and not updated since 2010, so I searched for a solution. =))))

Please, help me.

**Comment by gix** [comment]
The last authentication step is missing. You have to click the button again (it should say "Complete authentication") after the browser page is opened and you allow foo_scrobble on last.fm.

**Comment by gix** [comment]
Error 14 indicates that the auth token has not been authorized. You authorize it by clicking "Yes, allow access" on the last.fm page that should open in your browser when you click the authorize button within foobar.

**Comment by apometron** [comment]
I do clicked it friend.

**Comment by apometron** [comment]
I did tried several browsers....

**Comment by gix** [comment]
Order is important.

1. Click on the button in foobar2000 that says "Request authorization". The connect page on last.fm should open in your browser.
2. Click on "Yes, allow access" in your browser. Ensure last.fm shows a success message.
3. Click on the button in foobar2000 that should say "Complete authorization".

If the log still says error 14 despite all that then something is wrong on last.fm's side. I can't do anything about that.

**Comment by apometron** [comment]
The only player giving me problems is Foobar. Amarok works nicely but I like more Foobar. =)))

**Comment by apometron** [comment]
Do you use Chocolatey.org ?

**Comment by apometron** [comment]
Do you will contact them? Why AIMP, Musique and Amarok scrobble perfectly? =(

**Comment by apometron** [comment]
I will produce a GIF animation of the problem. It is the same you did in your movie explanation...

**Comment by apometron** [comment]
It seems it is something with Last.fm, because now it is working. I did all exactly as you did!!!

**Comment by apometron** [comment]
No need to do the GIF. Because now it is ok... Thanks for the help and it is a great plugin !!! =DDD

**Comment by xtay573269555** [comment]
I encountered the same problem. 

foo_scrobble: Requesting auth token
foo_scrobble: Received auth token: ChlrnKffSFmuG_rZdi7mMB1LpJ9uvAUx
foo_scrobble: Submitting 9 of 9 cached tracks
foo_scrobble: Scrobbling failed (error: 9, Invalid session key. Please re-authenticate.)

**Comment by gix** [comment]
> I clicked "Yes, allow access" in the browser, and then clicked "Apply" on the Foobar2000 setting window. The console print the above info.

Please see the linked video above and read the instructions on the authorization button. You are missing the final step "Complete authorization". Only after that click on "Apply".

**Comment by xtay573269555** [comment]
@gix Thanks, It works. I missed the step before.

I made some pictures of how to connect to LastFM using this plugin.
![p1](https://user-images.githubusercontent.com/5844466/38009588-937d7a28-3244-11e8-8b07-fa9c5b67ffe8.png)
![p2](https://user-images.githubusercontent.com/5844466/38009593-99cfbfd0-3244-11e8-8d08-59f7a716344a.png)
![p3](https://user-images.githubusercontent.com/5844466/38009595-a04e9106-3244-11e8-98d5-a33fd37a5e98.png)
![p4](https://user-images.githubusercontent.com/5844466/38009597-a4a645dc-3244-11e8-80bf-f6cbc8cb422f.png)
![p5](https://user-images.githubusercontent.com/5844466/38009604-a90636a0-3244-11e8-9e93-06a9e1991f00.png)
![p6](https://user-images.githubusercontent.com/5844466/38009607-ae2839f8-3244-11e8-8e15-461c167e3f6f.png)

**Comment by sanitysama** [comment]
This is a weird solution, but when I get the same problem: plug-in seems to be working fine, but just not submitting tracks, I have to do this: I clear authorization, request a new token, authorize foo_scrobble to connect to my last.fm account, then complete authorization. At this point it should be sending the cached tracks, however it does not yet. To fix this issue I have to change something in one of the fields to make the "Apply" button clickable, so **I just put a white space into the "Skip format:" field in foo_scrobble's options panel, hit apply, and suddenly all of my cached tracks were submitted**, confirmed by refreshing my last.fm account that they were submitted.

So I believe this is a small bug with the Skip Format field somehow evaluating as "all tracks should be skipped during submission." I could be wrong but this solution just makes it seems there's something fishy going on with this field.

I would suggest making a toggle for this particular field, so that no functions for its feature are computed at all if you are the type of user who does not use it. Everything in my library is properly tagged, and I do not care if last.fm gets poisoned or incorrect metadata from me.

Sorry if this sounds brash, because I really like this plug-in, it's a major improvement over the legacy component that required you to write your credentials into the settings panel (very unsafe), but that one and this one both have had the tendency to just stop doing what they're supposed to do, leaving the user in the dark. I've dumped tens of thousands of scrobbles due to errors. I'm just wondering what it takes to just make things "just work." or at least more user-attentive when something is going wrong.

Grateful for your hard work.
