### ISSUE TITLE
[REQ] foo_scrobble & foobar2000 v2 x64

### ISSUE THREAD

**Issue by Barough** [gix/foo_scrobble#42]
Please make the foo_scrobble component compatible with foobar2000 v2 x64.

The scrobble component still work just fine with v2 x86. :)

**Comment by marc2k3** [comment]
It would be great if this happens. I have my own component for pulling last.fm playcounts/first played/last played dates and presents them in fb2k for users to display/filter by etc.

https://marc2k3.github.io/component/lastfm-playcount-sync/

I've made a 64bit version available but it is kind of redundant without a scrobbler. 😀

I have 64bit code for submitting my own scrobbles but it's not something I'd share because I have zero options, no caching/retrying etc.

**Comment by Barough** [comment]
Thanks a lot :)
