### ISSUE TITLE
Use timestamp when track ended

### ISSUE THREAD

**Issue by Keiyuu** [gix/foo_scrobble#44]
I noticed that this scrobbler uses the timestamp when a track started playing. The official Last.fm scrobbler uses the time when a track has ended. I'm not sure if this is by design but I would prefer for it to use the end time instead of the start time.
It also makes more sense to me and is more accurate to track when you actually finished listening to something, especially with longer tracks or in situations where you paused during the song.

Maybe this could be an option to switch between both ways so users can pick what they prefer.

**Comment by bassstorm** [comment]
Agree that this feature should be configurable to user's preference.

**Comment by Keiyuu** [comment]
Any update on this? Is this something that's being considered?

**Comment by gix** [comment]
As can be seen in the [official documentation](https://www.last.fm/api/show/track.scrobble):

> timestamp[i] (Required) : The time the track started playing [...]

so this is very much by design, and also IMO intuitive: Would you say you've watched a movie at 8:00 prime time, or at 10:20 when it finished?

A track may also be scrobbled earlier once its conditions are met (at least 30 seconds, half of the song or at most 4 minutes) and the length may not be known beforehand.
