### ISSUE TITLE
component is missing a required dependency, or was made for a different version of foobar

### ISSUE THREAD

**Issue by nolovedeepweb** [gix/foo_scrobble#5]
I keep getting this error (https://imgur.com/a/2QFwVNO) after multiple re-installations of both foobar, the plugin, and  Visual C++ Redistributable for Visual Studio 2017. Not sure what the issue could be.

**Comment by apometron** [comment]
Strange, it is working nicely here, my version is the 1.4 beta 12.

I dont know to explain why it did not work when I was installing the plugin.

Suddenly it installed properly, I dont have any way to understand what happened.

Magically the problem vanished.

**Comment by apometron** [comment]
Since then it is working very well. I am sorry you are getting trouble. =(((

**Comment by apometron** [comment]
Try the beta 12 available at Foorbar2000 site.

**Comment by gix** [comment]
From the looks of the screenshot you seem to be using Windows 10.

Could you please download the latest Dependencies.zip from https://github.com/lucasg/Dependencies/releases and then open foo_scrobble.dll with it. The list on the left side shows all dependencies. Only shared.dll from foobar2000 should show a question mark icon (since it's in a different directory and not found).

**Comment by takerukoushirou** [comment]
I had the same issue using the latest 1.3 stable release, but it loads with the latest 1.4 beta (both running under Wine).

**Comment by gix** [comment]
Closing due to lack of feedback. Please re-open if the issue persists.
